import js from '@eslint/js'
import prettier from 'eslint-config-prettier'
import pluginVue from 'eslint-plugin-vue'
import tseslint from 'typescript-eslint'

export default tseslint.config(
  {
    ignores: [
      'dist/**',
      'coverage/**',
      'node_modules/**',
      'playwright-report/**',
      'test-results/**',
      // Generated by `npm run mock:init`; not ours to lint. It lives in mock/
      // rather than public/ so a build never copies it into a production image,
      // and it is served from the origin root by the plugin in vite.config.ts.
      'mock/mockServiceWorker.js',
    ],
  },
  js.configs.recommended,
  tseslint.configs.recommended,
  pluginVue.configs['flat/recommended'],
  {
    // .vue files need TypeScript inside the template's <script lang="ts">, so
    // the Vue parser delegates to the TS parser.
    files: ['**/*.vue'],
    languageOptions: {
      parserOptions: { parser: tseslint.parser },
    },
    rules: {
      // `typescript-eslint`'s own recommended set turns this off for .ts files
      // and cannot reach .vue ones, where eslint-plugin-vue has already put its
      // parser in charge. The call is the same here for the same reason:
      // `no-undef` cannot see a type-only declaration, so in a file that is
      // TypeScript it reports DOM globals (`HTMLDivElement`, `window`) as
      // undefined, and the compiler that CAN see them is already run by
      // `npm run typecheck`.
      'no-undef': 'off',
      // Ionic's components are custom elements, and `slot="start"` is how a
      // light-DOM child is placed in one of their named slots. The rule exists
      // to push Vue 2 components onto `v-slot`, which a custom element does not
      // have: there is no Vue 3 alternative to write here, so the rule is off
      // for ion-* and stays on everywhere else.
      //
      // The slashes are not decoration. A bare string in `ignore` is escaped and
      // anchored, so '^ion-' compiles to /^\^ion-$/ and matches nothing; only a
      // slash-delimited string is read as a pattern.
      'vue/no-deprecated-slot-attribute': ['error', { ignore: ['/^ion-/'] }],
    },
  },
  {
    // The design-system primitives are named for what they are (`Grid`,
    // `Panel`, `Toolbar`) and several props are meaningful precisely when they
    // are absent, so the Vue style rules that assume an app-level component
    // naming scheme and an always-present default do not apply to them.
    files: ['src/components/ui/**/*.vue'],
    rules: {
      'vue/multi-word-component-names': 'off',
      'vue/require-default-prop': 'off',
    },
  },
  // Last: turns off every rule Prettier owns. eslint-plugin-vue's
  // flat/recommended includes formatting rules that fight it.
  prettier,
)
