#!/bin/sh
# Exercise generate-secrets.sh twice against a throwaway copy of the
# deploy directory.
#
# It asserts three things the ticket calls out:
#   1. the generated root password and .env are 0600, and the admin_auth secrets
#      directory is 0711;
#   2. a second run does not change any generated byte, mode or mtime;
#   3. no secret value is ever printed by the script.
#
# The copy is under /tmp and holds only what the script reads: the script itself,
# .env.example and valkey/valkey.conf.example. No Docker, no Go and no database is
# touched.
#
# Usage: deploy/scripts/test-generate-secrets.sh

set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
GEN="$SCRIPT_DIR/generate-secrets.sh"

BASE=$(mktemp -d "${TMPDIR:-/tmp}/gen-secrets-test.XXXXXX")
trap 'rm -rf "$BASE"' EXIT INT TERM

DEST="$BASE/deploy"
mkdir -p "$DEST/scripts" "$DEST/valkey"
cp "$GEN" "$DEST/scripts/generate-secrets.sh"
cp "$SCRIPT_DIR/../.env.example" "$DEST/.env.example"
cp "$SCRIPT_DIR/../valkey/valkey.conf.example" "$DEST/valkey/valkey.conf.example"
chmod +x "$DEST/scripts/generate-secrets.sh"

ROOT_PASSWORD_FILE="$DEST/secrets/admin_auth/root_password"

fail() {
    echo "test-generate-secrets: FAIL: $1" >&2
    exit 1
}

pass() {
    echo "  ok: $1"
}

# snapshot <file>: one line per regular file, with its mode, mtime and checksum.
# Used to prove the second run changes nothing at all.
snapshot() {
    out=$1
    : > "$out"
    find "$DEST" -type f | LC_ALL=C sort | while IFS= read -r f; do
        printf '%s mode=%s mtime=%s cksum=%s\n' \
            "${f#$DEST/}" "$(stat -c '%a' "$f")" "$(stat -c '%y' "$f")" "$(cksum < "$f")"
    done >> "$out"
}

# assert_no_secrets <output-file>: every password value that now exists on disk must
# not appear in the captured output.
assert_no_secrets() {
    output=$1
    secret_file="$DEST/.env"

    root_value=$(cat "$ROOT_PASSWORD_FILE")
    [ -n "$root_value" ] || fail "root_password is empty"

    for v in "$root_value" $(sed -n 's/^[A-Z_]*PASSWORD=//p' "$secret_file") $(cat "$DEST"/secrets/service_keys/*.key); do
        [ -n "$v" ] || fail "an empty password was generated"
        if grep -Fq -- "$v" "$output"; then
            fail "a secret value appeared in generate-secrets.sh output"
        fi
    done
}

# --- first run ---------------------------------------------------------------

out1="$BASE/out1"
if ! sh "$DEST/scripts/generate-secrets.sh" > "$out1" 2>&1; then
    cat "$out1" >&2
    fail "first run exited non-zero"
fi

[ -f "$ROOT_PASSWORD_FILE" ] || fail "root_password was not created"
[ -f "$DEST/.env" ] || fail ".env was not created"
[ -f "$DEST/valkey/valkey.conf" ] || fail "valkey.conf was not created"

mode=$(stat -c '%a' "$ROOT_PASSWORD_FILE")
[ "$mode" = 600 ] || fail "root_password mode $mode, want 600"
mode=$(stat -c '%a' "$DEST/.env")
[ "$mode" = 600 ] || fail ".env mode $mode, want 600"
mode=$(stat -c '%a' "$DEST/secrets/admin_auth")
[ "$mode" = 711 ] || fail "secrets/admin_auth mode $mode, want 711"
mode=$(stat -c '%a' "$DEST/secrets")
[ "$mode" = 1777 ] || fail "secrets mode $mode, want 1777 (sticky)"
pass "root_password 0600, .env 0600, secrets/admin_auth 0711, secrets 1777"

case $(cat "$ROOT_PASSWORD_FILE") in
    *[!A-Za-z0-9]*) fail "root_password contains characters outside A-Za-z0-9" ;;
esac
[ "$(wc -c < "$ROOT_PASSWORD_FILE")" -eq 32 ] || fail "root_password is not 32 characters"
pass "root_password is 32 URL-safe characters"

# One service key per internal caller, 0600 in a 0711 directory, 43
# base64url characters (32 random bytes), and all five distinct.
mode=$(stat -c '%a' "$DEST/secrets/service_keys")
[ "$mode" = 711 ] || fail "secrets/service_keys mode $mode, want 711"
for name in allocator_session allocator_gameserver allocator_proxy session_allocator patch_session; do
    key_file="$DEST/secrets/service_keys/$name.key"
    [ -f "$key_file" ] || fail "service key $name.key was not created"
    mode=$(stat -c '%a' "$key_file")
    [ "$mode" = 600 ] || fail "$name.key mode $mode, want 600"
    case $(cat "$key_file") in
        *[!A-Za-z0-9_-]*) fail "$name.key is not base64url" ;;
    esac
    [ "$(wc -c < "$key_file")" -eq 43 ] || fail "$name.key is not 43 characters"
done
[ "$(for f in "$DEST"/secrets/service_keys/*.key; do cat "$f"; echo; done | sort -u | wc -l)" -eq 5 ] || fail "service keys are not distinct"
pass "service keys 0600 in a 0711 directory, 43 base64url characters, distinct"
mode=$(stat -c '%a' "$DEST/secrets/allocator")
[ "$mode" = 711 ] || fail "secrets/allocator mode $mode, want 711"
pass "secrets/allocator 0711"

assert_no_secrets "$out1"
pass "no secret value appears in the first run's output"

# --- second run --------------------------------------------------------------

snap1="$BASE/snap1"
snap2="$BASE/snap2"
snapshot "$snap1"

out2="$BASE/out2"
if ! sh "$DEST/scripts/generate-secrets.sh" > "$out2" 2>&1; then
    cat "$out2" >&2
    fail "second run exited non-zero"
fi

snapshot "$snap2"
if ! diff -u "$snap1" "$snap2" > "$BASE/snapshot.diff"; then
    cat "$BASE/snapshot.diff" >&2
    fail "second run changed a file's checksum, mode or mtime"
fi
pass "second run changed no checksum, mode or mtime"

assert_no_secrets "$out2"
pass "no secret value appears in the second run's output"

echo "test-generate-secrets: PASS"
