#!/usr/bin/env bash
#
# smoke.sh: end-to-end smoke test for the player edge (services/gateway).
#
# Everything here is local and ephemeral: no Docker, no database, no other
# service. Two Ed25519 keypairs are generated by testdata/smoke/keyserver.go and
# published as JWKS documents exactly as services/auth and PHP Admin Auth publish
# theirs; the tokens the checks present are minted against those keys. The
# upstreams are the echo servers in testdata/manual/fake_upstream.go, reused
# rather than duplicated.
#
# Run it from anywhere:
#
#     bash services/gateway/testdata/smoke/smoke.sh
#
# It builds from the working tree, starts everything, runs the checks, prints one
# line per check with the observed status and COM-5 code, and shuts everything
# down again. The output is still meant to be pasted and read, but every check
# with an expectation is also counted: a mismatch prints FAIL, a FINDING counts
# as a failure, and the script exits 1 unless everything passed. That exit code
# is what Jenkins gates on (ci/scripts/smoke.sh).
#
# Ports, none of which collide with testdata/manual's 8080/8081:
#
#     public listener     127.0.0.1:18080
#     metrics listener    127.0.0.1:18081
#     keyserver (JWKS)    127.0.0.1:18082
#     echo upstreams      127.0.0.1:9001 auth, 9002 patch, 9003 session
#
set -uo pipefail   # deliberately no -e: a failed check must print, not abort the run

HERE=$(cd "$(dirname "$0")" && pwd)
SVC=$(cd "$HERE/../.." && pwd)

PUB=127.0.0.1:18080
METRICS=127.0.0.1:18081
KEYS=127.0.0.1:18082
AUTH_UP=127.0.0.1:9001
PATCH_UP=127.0.0.1:9002
SESSION_UP=127.0.0.1:9003

# The subjects keyserver.go mints and the request id this script sends, so check
# 19 can grep /metrics for all three and find nothing.
PLAYER_SUBJECT=player-uuid-SMOKE-9012345
STAFF_SUBJECT=staff-uuid-SMOKE-6789012
SMOKE_REQ_ID=smoke-req-id-0001

WORK=$(mktemp -d)
GW_PID=""
UP_PID=""
KEYS_PID=""

cleanup() {
  [ -n "$GW_PID" ] && kill "$GW_PID" 2>/dev/null
  [ -n "$UP_PID" ] && kill "$UP_PID" 2>/dev/null
  [ -n "$KEYS_PID" ] && kill "$KEYS_PID" 2>/dev/null
  wait 2>/dev/null
  rm -rf "$WORK"
}
trap cleanup EXIT INT TERM

# This script builds the service from the working tree, so it needs the
# toolchain. Say so in one line rather than letting a missing `go` surface as a
# bare "command not found" from inside a subshell.
if ! command -v go >/dev/null 2>&1; then
  echo "go is not on PATH. This script builds the service from the working tree;"
  echo "on this machine: export PATH=\"\$HOME/go-toolchain/go/bin:\$PATH\""
  exit 1
fi

# hit <method> <url> [bearer-token]
#
# One request. Leaves the body in $WORK/body and prints
# "<status> <com5-code|-> [upstream=<name>]", so every check line shows what was
# actually observed rather than what was hoped for.
hit() {
  local method=$1 url=$2 token=${3:-}
  local args status code upstream
  args=(-s -o "$WORK/body" -w '%{http_code}' --max-time 10)
  [ -n "$token" ] && args+=(-H "Authorization: Bearer $token")
  status=$(curl "${args[@]}" -X "$method" "$url")
  code=$(grep -o '"code":"[a-z_]*"' "$WORK/body" 2>/dev/null | head -1 | cut -d'"' -f4)
  upstream=$(grep -o '"upstream": *"[^"]*"' "$WORK/body" 2>/dev/null | head -1 | cut -d'"' -f4)
  printf '%s %s%s' "$status" "${code:--}" "${upstream:+ upstream=$upstream}"
}

pass=0
fail=0

# expect <label> <observed> <want>
#
# One counted check line: "<label> -> <observed>   [expect <want>]", prefixed
# with FAIL on a mismatch. <want> is "<status> [<com5-code>] [upstream=<name>]";
# anything after ", " or ": " is a comment for the reader and is not compared.
# Only the words given are checked, so "200" alone accepts any body.
expect() {
  local label=$1 observed=$2 want=$3
  local core=${want%%, *} o_status o_code o_up w ok=1
  core=${core%%: *}
  read -r o_status o_code o_up <<<"$observed"
  for w in $core; do
    case $w in
      upstream=*) [ "$w" = "$o_up" ] || ok=0 ;;
      [0-9][0-9][0-9]) [ "$w" = "$o_status" ] || ok=0 ;;
      *) [ "$w" = "$o_code" ] || ok=0 ;;
    esac
  done
  if [ "$ok" = 1 ]; then
    pass=$((pass + 1))
    echo "    $label -> $observed   [expect $want]"
  else
    fail=$((fail + 1))
    echo "    FAIL: $label -> $observed   [expect $want]"
  fi
}

# finding <text>: a check that found something wrong. Counted as a failure.
finding() {
  fail=$((fail + 1))
  echo "    FINDING: $1"
}

# wait_ready <metrics-port>: poll /readyz until both JWKS domains have keys.
wait_ready() {
  local i
  for i in $(seq 1 200); do
    [ "$(curl -s -o /dev/null -w '%{http_code}' --max-time 2 "http://$1/readyz")" = "200" ] && return 0
    sleep 0.1
  done
  echo "TIMEOUT: http://$1/readyz never returned 200"
  return 1
}

# wait_upstream <host:port> <name>: poll until an echo server answers.
wait_upstream() {
  local i
  for i in $(seq 1 150); do
    curl -sf -o /dev/null --max-time 2 "http://$1/" && return 0
    sleep 0.1
  done
  echo "TIMEOUT: no upstream answering at $1 ($2); is another process already using that port?"
  return 1
}

echo "=== services/gateway smoke test (player edge) ==="
echo "public http://$PUB | metrics http://$METRICS | jwks http://$KEYS"
echo "upstreams http://$AUTH_UP (auth), http://$PATCH_UP (patch), http://$SESSION_UP (session)"
echo "work dir $WORK"

echo
echo "--- build from the working tree ---"
( cd "$SVC" && go build -o "$WORK/gateway" . ) || exit 1
( cd "$SVC" && go build -o "$WORK/keyserver" ./testdata/smoke/keyserver ) || exit 1
( cd "$SVC" && go build -o "$WORK/fake_upstream" ./testdata/manual ) || exit 1
echo "built gateway, keyserver and fake_upstream from $SVC"

echo
echo "--- start ---"
"$WORK/keyserver" -addr "$KEYS" -tokens "$WORK/tokens.env" > "$WORK/keyserver.log" 2>&1 &
KEYS_PID=$!
for _ in $(seq 1 100); do [ -s "$WORK/tokens.env" ] && break; sleep 0.1; done
if [ ! -s "$WORK/tokens.env" ]; then
  echo "keyserver never wrote its tokens:"
  cat "$WORK/keyserver.log"
  exit 1
fi
# shellcheck source=/dev/null
. "$WORK/tokens.env"
echo "keyserver on http://$KEYS: minted PLAYER_TOKEN, STAFF_NO_ROLES_TOKEN, STAFF_VIEWER_TOKEN, STAFF_LIVEOPS_TOKEN, STAFF_ADMIN_TOKEN"
echo "  player sub=$PLAYER_SUBJECT   staff sub=$STAFF_SUBJECT   (both SMOKE-tagged, so check 19 can grep for them)"

"$WORK/fake_upstream" > "$WORK/upstreams.log" 2>&1 &
UP_PID=$!
wait_upstream "$AUTH_UP" auth || exit 1
echo "echo upstreams on 9001-9007 (this service uses auth, patch and session)"

GATEWAY_LISTEN_ADDR="$PUB" \
GATEWAY_METRICS_ADDR="$METRICS" \
GATEWAY_PLAYER_JWKS_URL="http://$KEYS/.well-known/player-jwks.json" \
GATEWAY_PLAYER_ISSUER="https://auth.otomo.internal" \
GATEWAY_PLAYER_AUDIENCE="otomo:player" \
GATEWAY_STAFF_JWKS_URL="http://$KEYS/.well-known/staff-jwks.json" \
GATEWAY_STAFF_ISSUER="https://admin-auth.otomo.internal" \
GATEWAY_STAFF_AUDIENCE="otomo:staff" \
GATEWAY_UPSTREAM_AUTH_URL="http://$AUTH_UP" \
GATEWAY_UPSTREAM_PATCH_URL="http://$PATCH_UP" \
GATEWAY_UPSTREAM_SESSION_URL="http://$SESSION_UP" \
"$WORK/gateway" > "$WORK/gateway.log" 2>&1 &
GW_PID=$!
wait_ready "$METRICS" || { echo "gateway log:"; cat "$WORK/gateway.log"; exit 1; }
echo "gateway pid $GW_PID up; /readyz 200 (both JWKS domains fetched)"

echo
echo "=== checks ==="
echo
echo "--- 1. no token on a protected player route ---"
expect "GET /api/player/session/me" "$(hit GET "http://$PUB/api/player/session/me")" "401 missing_token"
echo "--- 2. a valid player token reaches the session upstream ---"
expect "GET /api/player/session/me (player)" "$(hit GET "http://$PUB/api/player/session/me" "$PLAYER_TOKEN")" "200 upstream=session"
echo "--- 3. a valid staff token on a player route: the player key is not in the staff registry ---"
expect "GET /api/player/session/me (staff)" "$(hit GET "http://$PUB/api/player/session/me" "$STAFF_ADMIN_TOKEN")" "401 invalid_signature"
echo "--- 4. a valid player token on the staff-only dev manifest ---"
expect "GET /patch/v1/dev/manifest (player)" "$(hit GET "http://$PUB/patch/v1/dev/manifest" "$PLAYER_TOKEN")" "401 invalid_signature, NOT iss_mismatch"
echo "--- 5. a valid staff token on the staff-only dev manifest ---"
expect "GET /patch/v1/dev/manifest (staff)" "$(hit GET "http://$PUB/patch/v1/dev/manifest" "$STAFF_ADMIN_TOKEN")" "200 upstream=patch"
echo "--- 6. every admin path 404s: the admin table is not in this binary ---"
for p in /api/admin/config/namespaces /api/admin/dashboard/logs/tail /api/admin/session/players /admin/dashboard /admin-auth/login; do
  expect "GET $p" "$(hit GET "http://$PUB$p")" "404 not_found"
done
echo "--- 7. internal endpoints: 404 on the public port, reachable on the metrics port ---"
for p in /healthz /readyz /metrics /debug/pprof/; do
  expect "public  http://$PUB$p" "$(hit GET "http://$PUB$p")" "404 not_found"
  expect "metrics http://$METRICS$p" "$(hit GET "http://$METRICS$p")" "200"
done
echo "--- 8. an unmatched path 404s in the COM-5 shape ---"
expect "GET /no/such/path" "$(hit GET "http://$PUB/no/such/path")" "404 not_found"
echo "    body: $(tr -d '\n' < "$WORK/body")"
echo "--- 9. the login route has the stricter rate limit (techspec §6.4: 5 rps, burst 10) ---"
# /auth/* is the brute-force target, so it has its own, smaller bucket. The 15
# requests go out from ONE curl process over one kept-alive connection: starting
# a curl per request is slow enough (notably on Windows) for the 5 rps refill to
# keep up, and no 429 would ever show. The other routes use the general limit
# (20 rps, burst 40) and are not affected.
login_args=()
for _ in $(seq 1 15); do login_args+=(-o /dev/null "http://$PUB/auth/login"); done
login_codes=$(curl -s -X POST -w '%{http_code} ' --max-time 10 "${login_args[@]}")
login_429=$(printf '%s\n' "$login_codes" | tr ' ' '\n' | grep -c '^429$')
echo "    15 x POST /auth/login back to back -> $login_codes  [expect 200s, then 429s from about request 11]"
expect "one more POST /auth/login" "$(hit POST "http://$PUB/auth/login")" "429 rate_limit_exceeded"
expect "GET /patch/v1/live/manifest straight after" "$(hit GET "http://$PUB/patch/v1/live/manifest")" "200 upstream=patch: separate bucket"
if [ "$login_429" -lt 1 ]; then
  finding "no 429 among 15 rapid logins; the login bucket is not enforced"
fi

echo
echo "--- 19. /metrics label cardinality ---"
# Two more requests first, so the scrape below has an identity to be wrong about:
# a request id and a subject that must not survive into a label.
curl -s -o /dev/null -H "X-Request-Id: $SMOKE_REQ_ID" "http://$PUB/api/player/session/me"
curl -s -o /dev/null -H "Authorization: Bearer $PLAYER_TOKEN" -H "X-Request-Id: $SMOKE_REQ_ID" "http://$PUB/api/player/session/me"
curl -s -o /dev/null -H "Authorization: Bearer $STAFF_ADMIN_TOKEN" -H "X-Request-Id: $SMOKE_REQ_ID" "http://$PUB/api/player/session/me"
curl -s "http://$METRICS/metrics" > "$WORK/metrics.txt"
echo "    gateway_* series and the label names on them (le excluded: it is a histogram bucket bound, not a label):"
awk -F'{' '$1 ~ /^gateway_[a-zA-Z_]+$/ {
             name = $1; labels = $2; sub(/}.*/, "", labels)
             n = split(labels, a, ","); names = ""
             for (i = 1; i <= n; i++) { split(a[i], b, "="); if (b[1] == "le") continue
                                        if (names != "") names = names ","; names = names b[1] }
             print "      " name " -> {" names "}"
           }' "$WORK/metrics.txt" | sort -u
if grep -qF -e "$SMOKE_REQ_ID" -e "$PLAYER_SUBJECT" -e "$STAFF_SUBJECT" "$WORK/metrics.txt"; then
  finding "an identity or request id reached /metrics:"
  grep -nF -e "$SMOKE_REQ_ID" -e "$PLAYER_SUBJECT" -e "$STAFF_SUBJECT" "$WORK/metrics.txt" | head
else
  echo "    no request id, player subject or staff subject appears anywhere in /metrics"
  echo "    (grepped for $SMOKE_REQ_ID, $PLAYER_SUBJECT, $STAFF_SUBJECT)"
fi

echo
echo "--- 20. metric names are the gateway_* series ---"
grep -E '^# HELP gateway_' "$WORK/metrics.txt" | sed 's/^/    /'
if grep -q '^gateway_dev_' "$WORK/metrics.txt"; then
  finding "a gateway_dev_* series exists here"
else
  echo "    no gateway_dev_* series: the gateway_* names are shared with gateway_dev on purpose,"
  echo "    see the package comment in internal/obslog/metrics.go before renaming anything"
fi

echo
echo "--- 21. shapes: one COM-5 body, one structured access log line ---"
echo "    COM-5 401 body: $(curl -s "http://$PUB/api/player/session/me" | tr -d '\n')"
echo "    COM-5 404 body: $(curl -s "http://$PUB/no/such/path" | tr -d '\n')"
echo "    access log, a rejection:"
grep -m1 '"reason":"missing_token"' "$WORK/gateway.log" | sed 's/^/      /'
echo "    access log, a proxied 200:"
grep -m1 '"status":200' "$WORK/gateway.log" | sed 's/^/      /'

echo
echo "=== done (gateway pid $GW_PID, keyserver pid $KEYS_PID, upstreams pid $UP_PID; all stopped on exit) ==="
echo "=== $pass passed, $fail failed ==="
[ "$fail" -eq 0 ] || exit 1
