import { mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'

import { expect, gotoApp, test, type Page } from './fixtures'

/**
 * The content-pack upload, against the fixture API in a real browser.
 *
 * The file is generated here rather than committed: a 100 MiB fixture in the
 * repository would be absurd, and the size is the point — a small file would
 * finish in one progress event and prove nothing about the bar. The same
 * generated bytes are uploaded twice, which is what exercises Config's sha256
 * dedupe answering 200 instead of 201.
 *
 * It is written to a temp file rather than handed to `setInputFiles` as a
 * buffer because Playwright refuses a buffer over 50 MiB ("please write it to a
 * file and pass its path instead"); the file name is preserved so the panel
 * still derives the same pack name.
 *
 * The upload progress is raised by the test rather than awaited from the
 * browser. MSW's service worker answers a mocked request inside the page, so the
 * body is buffered through the worker and Chromium emits no `xhr.upload`
 * progress for it at all — a passthrough request can emit some, but only
 * sometimes and never on demand. Everything the page does with a progress event
 * is still exercised: the events land on the real XMLHttpRequest's upload object
 * and travel through the same `onProgress` callback a network transfer uses.
 */

const HUNDRED_MB = 100 * 1024 * 1024

let packPath = ''

test.beforeAll(() => {
  const dir = mkdtempSync(join(tmpdir(), 'otomo-packs-'))
  packPath = join(dir, 'e2e_pack.pck')
  const bytes = Buffer.alloc(HUNDRED_MB)
  bytes.write('GDPC', 0, 'ascii')
  writeFileSync(packPath, bytes)
})

test.afterAll(() => {
  rmSync(dirname(packPath), { recursive: true, force: true })
})

async function signIn(page: Page, email: string): Promise<void> {
  await gotoApp(page, '/admin/login')
  await page.getByLabel('Email').fill(email)
  await page.getByLabel('Password').fill('x')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page).toHaveURL(/\/admin\/dashboard$/)
}

/**
 * Teach every XHR in the page to report its body leaving, a fraction at a time.
 *
 * The events are real `ProgressEvent`s on the real `upload` object, so the
 * client's `onProgress` and the bar's `aria-valuenow` see exactly what a network
 * upload would produce; only the source of the events is the test.
 */
async function reportUploadProgress(page: Page): Promise<void> {
  await page.addInitScript(() => {
    const originalSend = XMLHttpRequest.prototype.send
    XMLHttpRequest.prototype.send = function (
      this: XMLHttpRequest,
      body?: Document | XMLHttpRequestBodyInit | null,
    ): void {
      const size = body !== null && typeof body === 'object' && 'size' in body ? body.size : 0
      if (typeof size === 'number' && size > 0) {
        let loaded = 0
        const step = Math.max(1, Math.ceil(size / 8))
        const timer = window.setInterval(() => {
          loaded = Math.min(size, loaded + step)
          this.upload.dispatchEvent(
            new ProgressEvent('progress', { lengthComputable: true, loaded, total: size }),
          )
          if (loaded >= size) window.clearInterval(timer)
        }, 100)
      }
      originalSend.call(this, body)
    }
  })
}

/**
 * Record every value the progress bar's `aria-valuenow` takes.
 *
 * A MutationObserver rather than polling: the upload can move in a few frames,
 * and a sample loop would miss the intermediate values this test exists to
 * assert. The observer sees every attribute change even if the bar is only in
 * the DOM briefly.
 */
async function recordProgress(page: Page): Promise<void> {
  await page.evaluate(() => {
    const store = window as unknown as { __packProgress?: number[] }
    store.__packProgress = []
    const observer = new MutationObserver((mutations) => {
      for (const mutation of mutations) {
        if (mutation.type !== 'attributes') continue
        const target = mutation.target as Element
        if (target.getAttribute('role') !== 'progressbar') continue
        const raw = target.getAttribute('aria-valuenow')
        const value = raw === null ? Number.NaN : Number(raw)
        if (Number.isFinite(value)) store.__packProgress?.push(value)
      }
    })
    observer.observe(document.body, {
      attributes: true,
      attributeFilter: ['aria-valuenow'],
      subtree: true,
    })
  })
}

async function progressSamples(page: Page): Promise<number[]> {
  return page.evaluate(
    () => (window as unknown as { __packProgress?: number[] }).__packProgress ?? [],
  )
}

test('a live_ops upload shows progress and dedupes the second upload', async ({ page }) => {
  test.setTimeout(180_000)
  await reportUploadProgress(page)
  await signIn(page, 'liveops@example.com')
  await gotoApp(page, '/admin/config/packs')

  await page.getByTestId('pack-file-input').setInputFiles(packPath)

  // The name field is prefilled from the file name, without the extension.
  await expect(page.getByTestId('pack-name')).toHaveValue('e2e_pack')
  await expect(page.getByTestId('pack-file-summary')).toContainText('100 MiB')
  await expect(page.getByTestId('pack-upload-submit')).not.toHaveAttribute('aria-disabled', 'true')

  await recordProgress(page)
  await page.getByTestId('pack-upload-submit').click()

  await expect(page.getByTestId('pack-result')).toContainText('Uploaded', { timeout: 60_000 })
  await expect(page.getByTestId('pack-result')).toContainText(/[0-9a-f]{8}/)

  const samples = await progressSamples(page)
  expect(samples.length).toBeGreaterThan(0)
  expect(samples.some((value) => value > 0 && value < 100)).toBe(true)

  // The same bytes again: Config holds them, so the answer is 200 with the
  // first upload's row, and the page says so rather than showing a conflict.
  await page.getByTestId('pack-upload-submit').click()
  await expect(page.getByTestId('pack-result')).toContainText('Already uploaded — same bytes as', {
    timeout: 60_000,
  })
})

test('a file without the GDPC header is refused client-side', async ({ page }) => {
  await signIn(page, 'liveops@example.com')
  await gotoApp(page, '/admin/config/packs')

  await page.getByTestId('pack-file-input').setInputFiles({
    name: 'not_a_pack.pck',
    mimeType: 'application/octet-stream',
    buffer: Buffer.from([0x50, 0x4b, 0x03, 0x04, 0x00]),
  })

  await expect(page.getByTestId('pack-file-error')).toContainText('GDPC')
  await expect(page.getByTestId('pack-upload-submit')).toHaveAttribute('aria-disabled', 'true')
})
