#!/usr/bin/env bash
#
# smoke.sh: end-to-end smoke test for the admin/dev edge (services/gateway_dev).
#
# Everything here is local and ephemeral: no Docker, no database, no other
# service. Two Ed25519 keypairs are generated by testdata/smoke/keyserver and
# published as JWKS documents exactly as services/auth and admin-auth publish
# theirs; the tokens the checks present are minted against those keys. The
# upstreams are the echo servers in testdata/manual/fake_upstream.go, reused
# rather than duplicated, plus testdata/smoke/sseupstream for the dashboard: the
# streaming route's upstream needs to outlive the write timeout on purpose.
#
# Run it from anywhere:
#
#     bash services/gateway_dev/testdata/smoke/smoke.sh
#
# It builds from the working tree, starts everything, runs the checks, prints one
# line per check with the observed status and COM-5 code, and shuts everything
# down again. The output is still meant to be pasted and read, but every check
# with an expectation is also counted: a mismatch prints FAIL, a FINDING counts
# as a failure, and the script exits 1 unless everything passed. That exit code
# is what Jenkins gates on (ci/scripts/smoke.sh).
#
# Ports, none of which collide with testdata/manual's 8090/8091:
#
#     public listener     127.0.0.1:18090
#     metrics listener    127.0.0.1:18091
#     keyserver (JWKS)    127.0.0.1:18092
#     sse dashboard       127.0.0.1:18093
#     echo upstreams      127.0.0.1:9003 session, 9004 adminauth, 9005 adminui, 9006 config
#
set -uo pipefail   # deliberately no -e: a failed check must print, not abort the run

HERE=$(cd "$(dirname "$0")" && pwd)
SVC=$(cd "$HERE/../.." && pwd)

PUB=127.0.0.1:18090
METRICS=127.0.0.1:18091
KEYS=127.0.0.1:18092
SSE_UP=127.0.0.1:18093
SESSION_UP=127.0.0.1:9003
ADMINAUTH_UP=127.0.0.1:9004
ADMINUI_UP=127.0.0.1:9005
CONFIG_UP=127.0.0.1:9006

# The write timeout this script gives the gateway. Small so the run stays fast,
# and small enough that the SSE upstream's 3s hold exceeds it by a wide margin.
WRITE_TIMEOUT=2s

# The subjects keyserver mints and the request id this script sends, so check 19
# can grep /metrics for all three and find nothing.
PLAYER_SUBJECT=player-uuid-SMOKE-9012345
STAFF_SUBJECT=staff-uuid-SMOKE-6789012
SMOKE_REQ_ID=smoke-req-id-0001

WORK=$(mktemp -d)
GW_PID=""
UP_PID=""
SSE_PID=""
KEYS_PID=""

cleanup() {
  [ -n "$GW_PID" ] && kill "$GW_PID" 2>/dev/null
  [ -n "$SSE_PID" ] && kill "$SSE_PID" 2>/dev/null
  [ -n "$UP_PID" ] && kill "$UP_PID" 2>/dev/null
  [ -n "$KEYS_PID" ] && kill "$KEYS_PID" 2>/dev/null
  wait 2>/dev/null
  rm -rf "$WORK"
}
trap cleanup EXIT INT TERM

# This script builds the service from the working tree, so it needs the
# toolchain. Say so in one line rather than letting a missing `go` surface as a
# bare "command not found" from inside a subshell.
if ! command -v go >/dev/null 2>&1; then
  echo "go is not on PATH. This script builds the service from the working tree;"
  echo "on this machine: export PATH=\"\$HOME/go-toolchain/go/bin:\$PATH\""
  exit 1
fi

# hit <method> <url> [bearer-token]
#
# One request. Leaves the body in $WORK/body and prints
# "<status> <com5-code|-> [upstream=<name>]", so every check line shows what was
# actually observed rather than what was hoped for.
hit() {
  local method=$1 url=$2 token=${3:-}
  local args status code upstream
  args=(-s -o "$WORK/body" -w '%{http_code}' --max-time 10)
  [ -n "$token" ] && args+=(-H "Authorization: Bearer $token")
  status=$(curl "${args[@]}" -X "$method" "$url")
  code=$(grep -o '"code":"[a-z_]*"' "$WORK/body" 2>/dev/null | head -1 | cut -d'"' -f4)
  upstream=$(grep -o '"upstream": *"[^"]*"' "$WORK/body" 2>/dev/null | head -1 | cut -d'"' -f4)
  printf '%s %s%s' "$status" "${code:--}" "${upstream:+ upstream=$upstream}"
}

# hit_file <method> <url> <bearer-token> <body-file>
#
# Like hit, but sends a file as the request body. Used for the body-cap and
# content-pack checks, where the point is the body size rather than the path.
hit_file() {
  local method=$1 url=$2 token=$3 file=$4
  local args status code upstream
  args=(-s -o "$WORK/body" -w '%{http_code}' --max-time 60 -X "$method")
  [ -n "$token" ] && args+=(-H "Authorization: Bearer $token")
  args+=(--data-binary "@$file")
  status=$(curl "${args[@]}" "$url")
  code=$(grep -o '"code":"[a-z_]*"' "$WORK/body" 2>/dev/null | head -1 | cut -d'"' -f4)
  upstream=$(grep -o '"upstream": *"[^"]*"' "$WORK/body" 2>/dev/null | head -1 | cut -d'"' -f4)
  printf '%s %s%s' "$status" "${code:--}" "${upstream:+ upstream=$upstream}"
}

pass=0
fail=0

# expect <label> <observed> <want>
#
# One counted check line: "<label> -> <observed>   [expect <want>]", prefixed
# with FAIL on a mismatch. <want> is "<status> [<com5-code>] [upstream=<name>]";
# anything after ", " or ": " is a comment for the reader and is not compared.
# Only the words given are checked, so "200" alone accepts any body.
expect() {
  local label=$1 observed=$2 want=$3
  local core=${want%%, *} o_status o_code o_up w ok=1
  core=${core%%: *}
  read -r o_status o_code o_up <<<"$observed"
  for w in $core; do
    case $w in
      upstream=*) [ "$w" = "$o_up" ] || ok=0 ;;
      [0-9][0-9][0-9]) [ "$w" = "$o_status" ] || ok=0 ;;
      *) [ "$w" = "$o_code" ] || ok=0 ;;
    esac
  done
  if [ "$ok" = 1 ]; then
    pass=$((pass + 1))
    echo "    $label -> $observed   [expect $want]"
  else
    fail=$((fail + 1))
    echo "    FAIL: $label -> $observed   [expect $want]"
  fi
}

# finding <text>: a check that found something wrong. Counted as a failure.
finding() {
  fail=$((fail + 1))
  echo "    FINDING: $1"
}

# wait_ready <metrics-port>: poll /readyz until the staff JWKS domain has keys.
wait_ready() {
  local i
  for i in $(seq 1 200); do
    [ "$(curl -s -o /dev/null -w '%{http_code}' --max-time 2 "http://$1/readyz")" = "200" ] && return 0
    sleep 0.1
  done
  echo "TIMEOUT: http://$1/readyz never returned 200"
  return 1
}

# wait_upstream <host:port> <name>: poll until a fake upstream answers.
wait_upstream() {
  local i
  for i in $(seq 1 150); do
    curl -sf -o /dev/null --max-time 2 "http://$1/" && return 0
    sleep 0.1
  done
  echo "TIMEOUT: no upstream answering at $1 ($2); is another process already using that port?"
  return 1
}

echo "=== services/gateway_dev smoke test (admin/dev edge) ==="
echo "public http://$PUB | metrics http://$METRICS | jwks http://$KEYS | sse upstream http://$SSE_UP"
echo "echo upstreams http://$SESSION_UP (session), http://$ADMINAUTH_UP (adminauth), http://$ADMINUI_UP (adminui), http://$CONFIG_UP (config)"
echo "GATEWAY_DEV_WRITE_TIMEOUT=$WRITE_TIMEOUT"
echo "work dir $WORK"

echo
echo "--- build from the working tree ---"
( cd "$SVC" && go build -o "$WORK/gateway_dev" . ) || exit 1
( cd "$SVC" && go build -o "$WORK/keyserver" ./testdata/smoke/keyserver ) || exit 1
( cd "$SVC" && go build -o "$WORK/sseupstream" ./testdata/smoke/sseupstream ) || exit 1
( cd "$SVC" && go build -o "$WORK/fake_upstream" ./testdata/manual ) || exit 1
echo "built gateway_dev, keyserver, sseupstream and fake_upstream from $SVC"

echo
echo "--- start ---"
"$WORK/keyserver" -addr "$KEYS" -tokens "$WORK/tokens.env" > "$WORK/keyserver.log" 2>&1 &
KEYS_PID=$!
for _ in $(seq 1 100); do [ -s "$WORK/tokens.env" ] && break; sleep 0.1; done
if [ ! -s "$WORK/tokens.env" ]; then
  echo "keyserver never wrote its tokens:"
  cat "$WORK/keyserver.log"
  exit 1
fi
# shellcheck source=/dev/null
. "$WORK/tokens.env"
echo "keyserver on http://$KEYS: minted PLAYER_TOKEN, STAFF_NO_ROLES_TOKEN, STAFF_VIEWER_TOKEN, STAFF_LIVEOPS_TOKEN, STAFF_ADMIN_TOKEN"
echo "  player sub=$PLAYER_SUBJECT   staff sub=$STAFF_SUBJECT   (both SMOKE-tagged, so check 19 can grep for them)"

"$WORK/fake_upstream" > "$WORK/upstreams.log" 2>&1 &
UP_PID=$!
wait_upstream "$SESSION_UP" session || exit 1
echo "echo upstreams on 9001-9007 (this service uses session, adminauth, adminui, config)"

"$WORK/sseupstream" -addr "$SSE_UP" -hold 3s > "$WORK/sse.log" 2>&1 &
SSE_PID=$!
wait_upstream "$SSE_UP" "dashboard (sse)" || exit 1
echo "sse dashboard upstream on http://$SSE_UP: holds 3s between chunk-1 and chunk-2"

GATEWAY_DEV_LISTEN_ADDR="$PUB" \
GATEWAY_DEV_METRICS_ADDR="$METRICS" \
GATEWAY_DEV_WRITE_TIMEOUT="$WRITE_TIMEOUT" \
GATEWAY_DEV_UPSTREAM_ADMINAUTH_URL="http://$ADMINAUTH_UP" \
GATEWAY_DEV_UPSTREAM_ADMINUI_URL="http://$ADMINUI_UP" \
GATEWAY_DEV_UPSTREAM_CONFIG_URL="http://$CONFIG_UP" \
GATEWAY_DEV_UPSTREAM_DASHBOARD_URL="http://$SSE_UP" \
GATEWAY_DEV_UPSTREAM_SESSION_URL="http://$SESSION_UP" \
GATEWAY_STAFF_JWKS_URL="http://$KEYS/.well-known/staff-jwks.json" \
GATEWAY_STAFF_ISSUER="https://admin-auth.otomo.internal" \
GATEWAY_STAFF_AUDIENCE="otomo:staff" \
"$WORK/gateway_dev" > "$WORK/gateway.log" 2>&1 &
GW_PID=$!
wait_ready "$METRICS" || { echo "gateway log:"; cat "$WORK/gateway.log"; exit 1; }
echo "gateway_dev pid $GW_PID up; /readyz 200 (staff JWKS fetched)"

echo
echo "=== checks ==="
echo
echo "--- 9. no token on a protected admin route ---"
expect "GET /api/admin/config/namespaces" "$(hit GET "http://$PUB/api/admin/config/namespaces")" "401 missing_token"
echo "--- 10. a valid player token on a staff route: the player key is not in this registry ---"
expect "GET /api/admin/config/namespaces (player)" "$(hit GET "http://$PUB/api/admin/config/namespaces" "$PLAYER_TOKEN")" "401 invalid_signature"
echo "--- 11. a valid player token on another staff route: still 401, explicitly not 403 ---"
expect "GET /api/admin/session/players (player)" "$(hit GET "http://$PUB/api/admin/session/players" "$PLAYER_TOKEN")" "401 invalid_signature, NOT 403"
echo "--- 12. a staff token with no roles claim is valid but authorized for nothing ---"
expect "GET /api/admin/config/namespaces (no roles)" "$(hit GET "http://$PUB/api/admin/config/namespaces" "$STAFF_NO_ROLES_TOKEN")" "403 insufficient_role"
expect "GET /api/admin/dashboard/logs/tail (no roles)" "$(hit GET "http://$PUB/api/admin/dashboard/logs/tail" "$STAFF_NO_ROLES_TOKEN")" "403 insufficient_role"
echo "--- 13. the config prefix needs viewer: Config re-checks writes per route ---"
expect "GET /api/admin/config/namespaces (viewer) " "$(hit GET "http://$PUB/api/admin/config/namespaces" "$STAFF_VIEWER_TOKEN")" "200 upstream=config"
expect "GET /api/admin/config/namespaces (live_ops)" "$(hit GET "http://$PUB/api/admin/config/namespaces" "$STAFF_LIVEOPS_TOKEN")" "200 upstream=config"
expect "GET /api/admin/config/namespaces (admin)  " "$(hit GET "http://$PUB/api/admin/config/namespaces" "$STAFF_ADMIN_TOKEN")" "200 upstream=config"
echo "--- 14. ServeMux specificity: the releases route needs admin, and must not fall through to the viewer prefix ---"
expect "POST /api/admin/config/channels/live/releases (viewer)  " "$(hit POST "http://$PUB/api/admin/config/channels/live/releases" "$STAFF_VIEWER_TOKEN")" "403 insufficient_role"
expect "POST /api/admin/config/channels/live/releases (live_ops)" "$(hit POST "http://$PUB/api/admin/config/channels/live/releases" "$STAFF_LIVEOPS_TOKEN")" "403 insufficient_role"
expect "POST /api/admin/config/channels/live/releases (admin)   " "$(hit POST "http://$PUB/api/admin/config/channels/live/releases" "$STAFF_ADMIN_TOKEN")" "200 upstream=config"
echo "--- 14b. staff account management is admin-only, and the collection root is not redirected ---"
expect "GET /api/admin/users (viewer)  " "$(hit GET "http://$PUB/api/admin/users" "$STAFF_VIEWER_TOKEN")" "403 insufficient_role"
expect "GET /api/admin/users (live_ops)" "$(hit GET "http://$PUB/api/admin/users" "$STAFF_LIVEOPS_TOKEN")" "403 insufficient_role"
expect "GET /api/admin/users (admin)   " "$(hit GET "http://$PUB/api/admin/users" "$STAFF_ADMIN_TOKEN")" "200 upstream=adminauth, NOT 307"
expect "POST /api/admin/users (admin)  " "$(hit POST "http://$PUB/api/admin/users" "$STAFF_ADMIN_TOKEN")" "200 upstream=adminauth, NOT 307"
expect "PATCH /api/admin/users/some-id (admin)" "$(hit PATCH "http://$PUB/api/admin/users/some-id" "$STAFF_ADMIN_TOKEN")" "200 upstream=adminauth"
echo "--- 15. staff roles are ordinal: admin passes a viewer-minimum route ---"
expect "GET /api/admin/session/players (viewer)" "$(hit GET "http://$PUB/api/admin/session/players" "$STAFF_VIEWER_TOKEN")" "200 upstream=session"
expect "GET /api/admin/session/players (admin) " "$(hit GET "http://$PUB/api/admin/session/players" "$STAFF_ADMIN_TOKEN")" "200 upstream=session"
echo "--- 16. every player path 404s: the player table is not in this binary ---"
for p in /api/player/session/me /api/player/session/events /auth/login /patch/v1/live/manifest; do
  expect "GET $p" "$(hit GET "http://$PUB$p")" "404 not_found"
done
echo "--- extra: the two public routes reach their upstreams ---"
expect "GET /admin-auth/login" "$(hit GET "http://$PUB/admin-auth/login")" "200 upstream=adminauth"
expect "GET /admin/dashboard" "$(hit GET "http://$PUB/admin/dashboard")" "200 upstream=adminui"
expect "GET /no/such/path" "$(hit GET "http://$PUB/no/such/path")" "404 not_found"
echo "--- 17. internal endpoints: 404 on the public port, reachable on the metrics port ---"
for p in /healthz /readyz /metrics /debug/pprof/; do
  expect "public  http://$PUB$p" "$(hit GET "http://$PUB$p")" "404 not_found"
  expect "metrics http://$METRICS$p" "$(hit GET "http://$METRICS$p")" "200"
done

echo
echo "--- 18. the streaming route is not cut short by GATEWAY_DEV_WRITE_TIMEOUT=$WRITE_TIMEOUT ---"
echo "    GET /api/admin/dashboard/logs/tail (viewer); upstream writes chunk-1, holds 3s, writes chunk-2"
SSE_META=$(curl -s -N --max-time 20 -o "$WORK/sse.txt" -w '%{http_code} %{time_total}' \
  -H "Authorization: Bearer $STAFF_VIEWER_TOKEN" "http://$PUB/api/admin/dashboard/logs/tail")
SSE_EXIT=$?
echo "    status and time_total: $SSE_META   curl exit=$SSE_EXIT"
echo "    body: $(tr '\n' '|' < "$WORK/sse.txt")"
if grep -q 'chunk-1' "$WORK/sse.txt"; then echo "    chunk-1 arrived"; else finding "chunk-1 never arrived"; fi
if grep -q 'chunk-2' "$WORK/sse.txt"; then echo "    chunk-2 arrived too, after holding past the $WRITE_TIMEOUT write timeout"; else finding "chunk-2 missing: the response was cut at the write timeout"; fi
echo "    upstream log:"; sed 's/^/      /' "$WORK/sse.log"

echo
echo "--- 19. /metrics label cardinality ---"
# Requests first, so the scrape below has an identity to be wrong about: a
# request id and two subjects that must not survive into a label.
curl -s -o /dev/null -H "X-Request-Id: $SMOKE_REQ_ID" "http://$PUB/api/admin/config/namespaces"
curl -s -o /dev/null -H "Authorization: Bearer $STAFF_ADMIN_TOKEN" -H "X-Request-Id: $SMOKE_REQ_ID" "http://$PUB/api/admin/config/namespaces"
curl -s -o /dev/null -H "Authorization: Bearer $PLAYER_TOKEN" -H "X-Request-Id: $SMOKE_REQ_ID" "http://$PUB/api/admin/session/players"
curl -s "http://$METRICS/metrics" > "$WORK/metrics.txt"
echo "    gateway_* series and the label names on them (le excluded: it is a histogram bucket bound, not a label):"
awk -F'{' '$1 ~ /^gateway_[a-zA-Z_]+$/ {
             name = $1; labels = $2; sub(/}.*/, "", labels)
             n = split(labels, a, ","); names = ""
             for (i = 1; i <= n; i++) { split(a[i], b, "="); if (b[1] == "le") continue
                                        if (names != "") names = names ","; names = names b[1] }
             print "      " name " -> {" names "}"
           }' "$WORK/metrics.txt" | sort -u
if grep -qF -e "$SMOKE_REQ_ID" -e "$PLAYER_SUBJECT" -e "$STAFF_SUBJECT" "$WORK/metrics.txt"; then
  finding "an identity or request id reached /metrics:"
  grep -nF -e "$SMOKE_REQ_ID" -e "$PLAYER_SUBJECT" -e "$STAFF_SUBJECT" "$WORK/metrics.txt" | head
else
  echo "    no request id, player subject or staff subject appears anywhere in /metrics"
  echo "    (grepped for $SMOKE_REQ_ID, $PLAYER_SUBJECT, $STAFF_SUBJECT)"
fi

echo
echo "--- 20. metric names are the gateway_* series, not gateway_dev_* ---"
grep -E '^# HELP gateway_' "$WORK/metrics.txt" | sed 's/^/    /'
if grep -q '^gateway_dev_' "$WORK/metrics.txt"; then
  finding "a gateway_dev_* series exists here"
else
  echo "    no gateway_dev_* series: the gateway_* names are shared with services/gateway on purpose,"
  echo "    see the package comment in internal/obslog/metrics.go before renaming anything"
fi
echo "    rejection series observed:"
grep -E '^gateway_token_rejected_total' "$WORK/metrics.txt" | sed 's/^/      /'

echo
echo "--- 21. shapes: one COM-5 body, one structured access log line ---"
echo "    COM-5 401 body: $(curl -s "http://$PUB/api/admin/config/namespaces" | tr -d '\n')"
echo "    COM-5 403 body: $(curl -s -H "Authorization: Bearer $STAFF_VIEWER_TOKEN" "http://$PUB/api/admin/users" | tr -d '\n')"
echo "    COM-5 404 body: $(curl -s "http://$PUB/api/player/session/me" | tr -d '\n')"
echo "    access log, a 401 (a player token on a staff route):"
grep -m1 '"reason":"invalid_signature"' "$WORK/gateway.log" | sed 's/^/      /'
echo "    access log, a 403 (a staff token under-privileged):"
grep -m1 '"reason":"insufficient_role"' "$WORK/gateway.log" | sed 's/^/      /'

echo
echo "--- 21b. the default 1 MiB body cap rejects an oversized POST before the upstream ---"
head -c $((2 * 1024 * 1024)) /dev/zero > "$WORK/two_mib.bin"
expect "POST /api/admin/session/players (2 MiB, admin)" "$(hit_file POST "http://$PUB/api/admin/session/players" "$STAFF_ADMIN_TOKEN" "$WORK/two_mib.bin")" "413 body_too_large"

echo
echo "--- 21c. the content-pack route raises the cap to 512 MiB and stays live_ops-gated ---"
head -c $((3 * 1024 * 1024)) /dev/zero > "$WORK/three_mib.bin"
expect "POST /api/admin/config/packs (3 MiB, live_ops)" "$(hit_file POST "http://$PUB/api/admin/config/packs" "$STAFF_LIVEOPS_TOKEN" "$WORK/three_mib.bin")" "200 upstream=config"
expect "POST /api/admin/config/packs (3 MiB, viewer)  " "$(hit_file POST "http://$PUB/api/admin/config/packs" "$STAFF_VIEWER_TOKEN" "$WORK/three_mib.bin")" "403 insufficient_role"

echo
echo "--- 21d. SetForwarded replaces the client X-Forwarded-For with the peer only ---"
# This runs before check 22 on purpose: check 22 drains the /admin-auth/ login
# bucket, and this request must be served rather than 429ed.
FWD_STATUS=$(curl -s -o "$WORK/body" -w '%{http_code}' --max-time 10 -X POST \
  -H "X-Forwarded-For: 6.6.6.6" "http://$PUB/admin-auth/login")
FWD_XFF=$(grep -o '"x_forwarded_for": *"[^"]*"' "$WORK/body" | head -1 | cut -d'"' -f4)
FWD_PROTO=$(grep -o '"x_forwarded_proto": *"[^"]*"' "$WORK/body" | head -1 | cut -d'"' -f4)
expect "POST /admin-auth/login with X-Forwarded-For: 6.6.6.6" "$FWD_STATUS" "200"
echo "    upstream saw X-Forwarded-For=$FWD_XFF X-Forwarded-Proto=$FWD_PROTO   [expect 127.0.0.1 and http, not 6.6.6.6]"
if [ "$FWD_XFF" = "6.6.6.6" ]; then
  finding "the client-supplied X-Forwarded-For 6.6.6.6 reached the upstream"
fi
if [ "$FWD_XFF" != "127.0.0.1" ]; then
  finding "upstream X-Forwarded-For is '$FWD_XFF', want the peer 127.0.0.1"
fi

echo
echo "--- 22. /admin-auth/ logins are rate limited (techspec §6.4: 5 rps, burst 10) ---"
# One curl process, one kept-alive connection: 12 requests back to back, so the
# 5 rps refill cannot keep up. The 12th is the interesting one: the login bucket
# is separate from the general limit, so /admin-auth/ 429s while other routes
# keep serving.
login_args=()
for _ in $(seq 1 12); do login_args+=(-o /dev/null "http://$PUB/admin-auth/login"); done
login_codes=$(curl -s -X POST -w '%{http_code} ' --max-time 10 "${login_args[@]}")
login_429=$(printf '%s\n' "$login_codes" | tr ' ' '\n' | grep -c '^429$')
echo "    12 x POST /admin-auth/login back to back -> $login_codes  [expect at least one 429]"
expect "one more POST /admin-auth/login" "$(hit POST "http://$PUB/admin-auth/login")" "429 rate_limit_exceeded"
if [ "$login_429" -ge 1 ]; then
  echo "    $login_429 of 12 rapid logins were 429 rate_limit_exceeded"
else
  finding "no 429 among 12 rapid logins; the login bucket is not enforced"
fi

echo
echo "=== done (gateway_dev pid $GW_PID, keyserver pid $KEYS_PID, sse upstream pid $SSE_PID, upstreams pid $UP_PID; all stopped on exit) ==="
echo "=== $pass passed, $fail failed ==="
[ "$fail" -eq 0 ] || exit 1
