package server_test

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/otomo-live/otomo/services/admin_auth/internal/mfa"
	"github.com/otomo-live/otomo/services/admin_auth/internal/password"
	"github.com/otomo-live/otomo/services/admin_auth/internal/server"
	"github.com/otomo-live/otomo/services/admin_auth/internal/token"
)

// mfaEnv is the session harness with the TOTP key and a frozen clock, so a code
// generated by the test validates in the handler no matter when the suite runs.
type mfaEnv struct {
	*sessionEnv
	key []byte
	now time.Time
}

func newMFAEnv(t *testing.T) *mfaEnv {
	t.Helper()

	db := loginDB(t)
	cfg := loginConfig()
	signer, pub, raw := newLoginSigner(t, cfg)
	verifier := token.NewVerifier(cfg.Issuer, cfg.Audience, []token.PublicKey{{Kid: loginKid, Key: pub}})
	key, err := mfa.GenerateKey()
	if err != nil {
		t.Fatalf("GenerateKey: %v", err)
	}
	now := time.Now().UTC().Truncate(time.Second)

	h := newHarnessWithConfig(t, cfg, server.Deps{
		JWKS:     fakeJWKS{raw: raw},
		Signer:   signer,
		Verifier: verifier,
		Store:    db,
		MFAKey:   key,
		MFANow:   func() time.Time { return now },
	})
	return &mfaEnv{
		sessionEnv: &sessionEnv{h: h, db: db, cfg: cfg, signer: signer, pub: pub},
		key:        key,
		now:        now,
	}
}

// staff inserts an account and, when confirmed, gives it a confirmed TOTP factor. It
// returns the raw secret so the test can generate a matching code.
func (e *mfaEnv) staff(t *testing.T, roles []string, confirmed bool) (id, email, pw string, secret []byte) {
	t.Helper()

	email = uniqueLoginEmail("mfa")
	pw = "password-" + email
	id = insertStaff(t, e.db, email, "MFA Staff", pw, roles)
	if !confirmed {
		return id, email, pw, nil
	}

	secret, err := mfa.GenerateSecret()
	if err != nil {
		t.Fatalf("GenerateSecret: %v", err)
	}
	sealed, err := mfa.Seal(e.key, id, secret)
	if err != nil {
		t.Fatalf("Seal: %v", err)
	}
	if _, err := e.db.Pool.Exec(context.Background(),
		`UPDATE staff_user SET totp_secret_enc = $2, totp_confirmed_at = now() WHERE id = $1::uuid`,
		id, sealed); err != nil {
		t.Fatalf("confirm TOTP fixture: %v", err)
	}
	return id, email, pw, secret
}

// code returns the TOTP for secret on the env's frozen clock.
func (e *mfaEnv) code(secret []byte) string {
	return mfa.Code(secret, e.now, 6)
}

// postJSON sends one JSON request with an optional bearer.
func postJSON(t *testing.T, base, path, tok, body string) (int, http.Header, string) {
	t.Helper()

	req, err := http.NewRequest(http.MethodPost, base+path, strings.NewReader(body))
	if err != nil {
		t.Fatalf("NewRequest: %v", err)
	}
	req.Header.Set("Content-Type", "application/json")
	if tok != "" {
		req.Header.Set("Authorization", "Bearer "+tok)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		t.Fatalf("POST %s: %v", path, err)
	}
	defer resp.Body.Close()
	raw, err := io.ReadAll(resp.Body)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	return resp.StatusCode, resp.Header, string(raw)
}

type mfaChallengeWire struct {
	MFARequired           bool   `json:"mfa_required"`
	MFAEnrollmentRequired bool   `json:"mfa_enrollment_required"`
	MFATicket             string `json:"mfa_ticket"`
	AccessToken           string `json:"access_token"`
}

type mfaEnrollWire struct {
	Secret     string `json:"secret"`
	OTPAuthURL string `json:"otpauth_url"`
}

type mfaConfirmWire struct {
	RecoveryCodes []string `json:"recovery_codes"`
	AccessToken   string   `json:"access_token"`
	ExpiresIn     int64    `json:"expires_in"`
	User          *struct {
		ID    string   `json:"id"`
		Name  string   `json:"name"`
		Roles []string `json:"roles"`
	} `json:"user"`
}

func decodeMFAChallenge(t *testing.T, body string) mfaChallengeWire {
	t.Helper()
	var got mfaChallengeWire
	if err := json.Unmarshal([]byte(body), &got); err != nil {
		t.Fatalf("challenge body %q is not JSON: %v", body, err)
	}
	return got
}

// loginTicket logs in and returns the challenge body.
func loginTicket(t *testing.T, e *mfaEnv, email, pw string) mfaChallengeWire {
	t.Helper()

	status, header, body := postLogin(t, e.h.public, fmt.Sprintf(`{"email":%q,"password":%q}`, email, pw))
	if status != http.StatusOK {
		t.Fatalf("login status = %d, want 200 (body %s)", status, body)
	}
	if set := header.Get("Set-Cookie"); set != "" {
		t.Fatalf("challenge login set a cookie: %q", set)
	}
	return decodeMFAChallenge(t, body)
}

// ticketPurpose reads one ticket's purpose straight from the database.
func ticketPurpose(t *testing.T, e *mfaEnv, ticket string) string {
	t.Helper()

	hash := sha256.Sum256([]byte(ticket))
	var purpose string
	if err := e.db.Pool.QueryRow(context.Background(),
		`SELECT purpose FROM mfa_ticket WHERE token_hash = $1`, hash[:]).Scan(&purpose); err != nil {
		t.Fatalf("read ticket purpose: %v", err)
	}
	return purpose
}

// insertRoot replaces any existing root with a fresh one and returns its id, email and
// a token. It mirrors the helper the user-management tests use.
func (e *mfaEnv) insertRoot(t *testing.T, pw string) (id, email string) {
	t.Helper()
	ctx := context.Background()

	_, _ = e.db.Pool.Exec(ctx, `DELETE FROM staff_invite WHERE created_by IN (SELECT id FROM staff_user WHERE is_root) OR user_id IN (SELECT id FROM staff_user WHERE is_root)`)
	_, _ = e.db.Pool.Exec(ctx, `DELETE FROM staff_user WHERE is_root`)

	hash, err := password.Hash(pw)
	if err != nil {
		t.Fatalf("password.Hash: %v", err)
	}
	email = uniqueLoginEmail("mfaroot")
	if err := e.db.Pool.QueryRow(ctx,
		`INSERT INTO staff_user (email, name, password_hash, roles, is_root)
		 VALUES ($1, $2, $3, ARRAY['admin'], true) RETURNING id::text`,
		email, "Root MFA", hash).Scan(&id); err != nil {
		t.Fatalf("insert root: %v", err)
	}
	t.Cleanup(func() {
		_, _ = e.db.Pool.Exec(context.Background(), `DELETE FROM staff_user WHERE id = $1::uuid`, id)
	})
	return id, email
}

func TestLoginRootWithConfirmedFactorStillGetsTokens(t *testing.T) {
	env := newMFAEnv(t)
	id, email := env.insertRoot(t, "root-password-1234")

	// Even a root that somehow has a confirmed factor is exempt.
	secret, _ := mfa.GenerateSecret()
	sealed, _ := mfa.Seal(env.key, id, secret)
	if _, err := env.db.Pool.Exec(t.Context(),
		`UPDATE staff_user SET totp_secret_enc = $2, totp_confirmed_at = now() WHERE id = $1::uuid`,
		id, sealed); err != nil {
		t.Fatalf("confirm root fixture: %v", err)
	}

	status, header, body := postLogin(t, env.h.public, fmt.Sprintf(`{"email":%q,"password":%q}`, email, "root-password-1234"))
	if status != http.StatusOK {
		t.Fatalf("root login status = %d, want 200 (body %s)", status, body)
	}
	if got := decodeLoginBody(t, body); got.AccessToken == "" {
		t.Error("root login returned no access token")
	}
	cookieFromHeader(t, header, testRefreshCookieName)
}

func TestLoginConfirmedFactorChallengesWithNoCookie(t *testing.T) {
	env := newMFAEnv(t)
	_, email, pw, _ := env.staff(t, []string{"live_ops"}, true)

	status, header, body := postLogin(t, env.h.public, fmt.Sprintf(`{"email":%q,"password":%q}`, email, pw))
	if status != http.StatusOK {
		t.Fatalf("status = %d, want 200 (body %s)", status, body)
	}
	if set := header.Get("Set-Cookie"); set != "" {
		t.Errorf("mfa_required login set a cookie: %q", set)
	}
	got := decodeMFAChallenge(t, body)
	if !got.MFARequired || got.MFAEnrollmentRequired {
		t.Errorf("challenge = %+v, want mfa_required only", got)
	}
	if got.MFATicket == "" {
		t.Error("mfa_ticket is empty")
	}
	if got.AccessToken != "" || strings.Contains(body, "access_token") {
		t.Error("the challenge body carries an access token")
	}
	if purpose := ticketPurpose(t, env, got.MFATicket); purpose != "verify" {
		t.Errorf("ticket purpose = %q, want verify", purpose)
	}
}

func TestLoginAdminWithoutTOTPRequiresEnrollment(t *testing.T) {
	env := newMFAEnv(t)
	id, email, pw, _ := env.staff(t, []string{"admin"}, false)

	// A password that was accepted must not clear the failure counter until a
	// session is actually issued.
	if _, err := env.db.Pool.Exec(t.Context(),
		`UPDATE staff_user SET failed_logins = 3 WHERE id = $1::uuid`, id); err != nil {
		t.Fatalf("seed failed_logins: %v", err)
	}

	got := loginTicket(t, env, email, pw)
	if !got.MFAEnrollmentRequired || got.MFARequired {
		t.Errorf("challenge = %+v, want mfa_enrollment_required only", got)
	}
	if purpose := ticketPurpose(t, env, got.MFATicket); purpose != "enroll" {
		t.Errorf("ticket purpose = %q, want enroll", purpose)
	}

	var failed int
	if err := env.db.Pool.QueryRow(t.Context(),
		`SELECT failed_logins FROM staff_user WHERE id = $1::uuid`, id).Scan(&failed); err != nil {
		t.Fatalf("read failed_logins: %v", err)
	}
	if failed != 3 {
		t.Errorf("failed_logins = %d, want 3 (unchanged until a session is issued)", failed)
	}
}

func TestLoginViewerWithoutTOTPStillGetsTokens(t *testing.T) {
	env := newMFAEnv(t)
	_, email, pw, _ := env.staff(t, []string{"viewer"}, false)

	status, header, body := postLogin(t, env.h.public, fmt.Sprintf(`{"email":%q,"password":%q}`, email, pw))
	if status != http.StatusOK {
		t.Fatalf("status = %d, want 200 (body %s)", status, body)
	}
	if got := decodeLoginBody(t, body); got.AccessToken == "" {
		t.Error("viewer without TOTP got no access token")
	}
	cookieFromHeader(t, header, testRefreshCookieName)
}

func TestMFAVerifyTOTPIssuesSession(t *testing.T) {
	env := newMFAEnv(t)
	id, email, pw, secret := env.staff(t, []string{"live_ops"}, true)

	ch := loginTicket(t, env, email, pw)
	status, header, body := postJSON(t, env.h.public, "/admin-auth/mfa/verify", "",
		fmt.Sprintf(`{"mfa_ticket":%q,"code":%q}`, ch.MFATicket, env.code(secret)))
	if status != http.StatusOK {
		t.Fatalf("verify status = %d, want 200 (body %s)", status, body)
	}
	got := decodeLoginBody(t, body)
	if got.AccessToken == "" {
		t.Error("verify returned no access token")
	}
	if got.User.ID != id {
		t.Errorf("verify user id = %q, want %s", got.User.ID, id)
	}
	cookieFromHeader(t, header, testRefreshCookieName)

	var method string
	if err := env.db.Pool.QueryRow(t.Context(),
		`SELECT details->>'mfa' FROM audit_log WHERE action = 'login.success' AND actor_id = $1 ORDER BY id DESC LIMIT 1`,
		id).Scan(&method); err != nil {
		t.Fatalf("read login.success details: %v", err)
	}
	if method != "totp" {
		t.Errorf("login.success mfa detail = %q, want totp", method)
	}
}

func TestMFAVerifyRejectsReplayedTOTP(t *testing.T) {
	env := newMFAEnv(t)
	_, email, pw, secret := env.staff(t, []string{"live_ops"}, true)
	code := env.code(secret)

	first := loginTicket(t, env, email, pw)
	if status, _, body := postJSON(t, env.h.public, "/admin-auth/mfa/verify", "",
		fmt.Sprintf(`{"mfa_ticket":%q,"code":%q}`, first.MFATicket, code)); status != http.StatusOK {
		t.Fatalf("first verify status = %d, want 200 (body %s)", status, body)
	}

	second := loginTicket(t, env, email, pw)
	status, _, body := postJSON(t, env.h.public, "/admin-auth/mfa/verify", "",
		fmt.Sprintf(`{"mfa_ticket":%q,"code":%q}`, second.MFATicket, code))
	if status != http.StatusUnauthorized {
		t.Fatalf("replay status = %d, want 401 (body %s)", status, body)
	}
	if got := decodeAPIError(t, body); got.Error.Code != "invalid_code" {
		t.Errorf("replay code = %q, want invalid_code", got.Error.Code)
	}
}

func TestMFAVerifyRecoveryCodeWorksOnce(t *testing.T) {
	env := newMFAEnv(t)
	id, email, pw, _ := env.staff(t, []string{"live_ops"}, true)

	codes, err := mfa.RecoveryCodes(3)
	if err != nil {
		t.Fatalf("RecoveryCodes: %v", err)
	}
	for _, code := range codes {
		if _, err := env.db.Pool.Exec(t.Context(),
			`INSERT INTO mfa_recovery_code (user_id, code_hash) VALUES ($1::uuid, $2)`,
			id, mfa.HashRecoveryCode(code)); err != nil {
			t.Fatalf("insert recovery code: %v", err)
		}
	}

	ch := loginTicket(t, env, email, pw)
	status, _, body := postJSON(t, env.h.public, "/admin-auth/mfa/verify", "",
		fmt.Sprintf(`{"mfa_ticket":%q,"code":%q}`, ch.MFATicket, strings.ToUpper(codes[0])))
	if status != http.StatusOK {
		t.Fatalf("recovery verify status = %d, want 200 (body %s)", status, body)
	}
	got := decodeLoginBody(t, body)
	if got.AccessToken == "" {
		t.Error("recovery verify returned no access token")
	}

	var method string
	var remaining string
	if err := env.db.Pool.QueryRow(t.Context(),
		`SELECT details->>'mfa' FROM audit_log WHERE action = 'login.success' AND actor_id = $1 ORDER BY id DESC LIMIT 1`,
		id).Scan(&method); err != nil {
		t.Fatalf("read login.success details: %v", err)
	}
	if method != "recovery_code" {
		t.Errorf("login.success mfa detail = %q, want recovery_code", method)
	}
	if err := env.db.Pool.QueryRow(t.Context(),
		`SELECT details->>'remaining' FROM audit_log WHERE action = 'mfa.recovery_used' AND actor_id = $1 ORDER BY id DESC LIMIT 1`,
		id).Scan(&remaining); err != nil {
		t.Fatalf("read mfa.recovery_used details: %v", err)
	}
	if remaining != "2" {
		t.Errorf("remaining = %q, want 2", remaining)
	}

	// The same code cannot be used again, even on a fresh ticket.
	ch2 := loginTicket(t, env, email, pw)
	status, _, body = postJSON(t, env.h.public, "/admin-auth/mfa/verify", "",
		fmt.Sprintf(`{"mfa_ticket":%q,"code":%q}`, ch2.MFATicket, codes[0]))
	if status != http.StatusUnauthorized {
		t.Fatalf("second recovery use status = %d, want 401 (body %s)", status, body)
	}
}

func TestMFAVerifyBurnsTicketAfterFiveWrongCodes(t *testing.T) {
	env := newMFAEnv(t)
	_, email, pw, secret := env.staff(t, []string{"live_ops"}, true)

	ch := loginTicket(t, env, email, pw)
	for i := 0; i < 5; i++ {
		status, _, body := postJSON(t, env.h.public, "/admin-auth/mfa/verify", "",
			fmt.Sprintf(`{"mfa_ticket":%q,"code":"000000"}`, ch.MFATicket))
		if status != http.StatusUnauthorized {
			t.Fatalf("wrong code %d status = %d, want 401 (body %s)", i+1, status, body)
		}
	}

	hash := sha256.Sum256([]byte(ch.MFATicket))
	var attempts int
	if err := env.db.Pool.QueryRow(t.Context(),
		`SELECT failed_attempts FROM mfa_ticket WHERE token_hash = $1`, hash[:]).Scan(&attempts); err != nil {
		t.Fatalf("read ticket: %v", err)
	}
	if attempts != 5 {
		t.Errorf("failed_attempts = %d after five wrong codes, want 5", attempts)
	}

	// Even the right code no longer works on a burned ticket.
	status, _, body := postJSON(t, env.h.public, "/admin-auth/mfa/verify", "",
		fmt.Sprintf(`{"mfa_ticket":%q,"code":%q}`, ch.MFATicket, env.code(secret)))
	if status != http.StatusUnauthorized {
		t.Fatalf("verify on a burned ticket = %d, want 401 (body %s)", status, body)
	}
	if got := decodeAPIError(t, body); got.Error.Code != "invalid_ticket" {
		t.Errorf("burned ticket code = %q, want invalid_ticket", got.Error.Code)
	}
}

func TestMFAVerifyRejectsExpiredTicket(t *testing.T) {
	env := newMFAEnv(t)
	_, email, pw, secret := env.staff(t, []string{"live_ops"}, true)

	ch := loginTicket(t, env, email, pw)
	hash := sha256.Sum256([]byte(ch.MFATicket))
	if _, err := env.db.Pool.Exec(t.Context(),
		`UPDATE mfa_ticket SET created_at = now() - interval '10 minutes', expires_at = now() - interval '5 minutes' WHERE token_hash = $1`,
		hash[:]); err != nil {
		t.Fatalf("expire ticket: %v", err)
	}

	status, _, body := postJSON(t, env.h.public, "/admin-auth/mfa/verify", "",
		fmt.Sprintf(`{"mfa_ticket":%q,"code":%q}`, ch.MFATicket, env.code(secret)))
	if status != http.StatusUnauthorized {
		t.Fatalf("expired ticket status = %d, want 401 (body %s)", status, body)
	}
	if got := decodeAPIError(t, body); got.Error.Code != "invalid_ticket" {
		t.Errorf("expired ticket code = %q, want invalid_ticket", got.Error.Code)
	}
}

func TestMFAVerifyRejectsEnrollTicket(t *testing.T) {
	env := newMFAEnv(t)
	_, email, pw, _ := env.staff(t, []string{"admin"}, false)

	ch := loginTicket(t, env, email, pw)
	status, _, body := postJSON(t, env.h.public, "/admin-auth/mfa/verify", "",
		fmt.Sprintf(`{"mfa_ticket":%q,"code":"123456"}`, ch.MFATicket))
	if status != http.StatusUnauthorized {
		t.Fatalf("enroll ticket on verify status = %d, want 401 (body %s)", status, body)
	}
	if got := decodeAPIError(t, body); got.Error.Code != "invalid_ticket" {
		t.Errorf("code = %q, want invalid_ticket", got.Error.Code)
	}
}

func TestMFAVerifyRejectsAccountDisabledMeanwhile(t *testing.T) {
	env := newMFAEnv(t)
	id, email, pw, secret := env.staff(t, []string{"live_ops"}, true)

	ch := loginTicket(t, env, email, pw)
	if _, err := env.db.Pool.Exec(t.Context(),
		`UPDATE staff_user SET status = 'disabled' WHERE id = $1::uuid`, id); err != nil {
		t.Fatalf("disable staff: %v", err)
	}

	status, _, body := postJSON(t, env.h.public, "/admin-auth/mfa/verify", "",
		fmt.Sprintf(`{"mfa_ticket":%q,"code":%q}`, ch.MFATicket, env.code(secret)))
	if status != http.StatusUnauthorized {
		t.Fatalf("disabled account status = %d, want 401 (body %s)", status, body)
	}
	if got := decodeAPIError(t, body); got.Error.Code != "invalid_ticket" {
		t.Errorf("code = %q, want invalid_ticket", got.Error.Code)
	}
}

func TestMFAEnrollConfirmTicketFlow(t *testing.T) {
	env := newMFAEnv(t)
	id, email, pw, _ := env.staff(t, []string{"admin"}, false)

	ch := loginTicket(t, env, email, pw)
	if !ch.MFAEnrollmentRequired {
		t.Fatalf("login challenge = %+v, want mfa_enrollment_required", ch)
	}

	status, _, body := postJSON(t, env.h.public, "/admin-auth/mfa/enroll", "",
		fmt.Sprintf(`{"mfa_ticket":%q}`, ch.MFATicket))
	if status != http.StatusOK {
		t.Fatalf("enroll status = %d, want 200 (body %s)", status, body)
	}
	var enrolled mfaEnrollWire
	if err := json.Unmarshal([]byte(body), &enrolled); err != nil {
		t.Fatalf("enroll body %q is not JSON: %v", body, err)
	}
	if enrolled.Secret == "" || !strings.HasPrefix(enrolled.OTPAuthURL, "otpauth://totp/Otomo%20Admin:") {
		t.Errorf("enroll response = %+v, want a secret and otpauth URL", enrolled)
	}
	secret, err := mfa.DecodeSecret(enrolled.Secret)
	if err != nil {
		t.Fatalf("DecodeSecret: %v", err)
	}

	// The secret is stored sealed and still unconfirmed; the enroll ticket is not
	// consumed, so it can be used for the confirm step.
	var (
		sealed    []byte
		confirmed *time.Time
	)
	if err := env.db.Pool.QueryRow(t.Context(),
		`SELECT totp_secret_enc, totp_confirmed_at FROM staff_user WHERE id = $1::uuid`, id).Scan(&sealed, &confirmed); err != nil {
		t.Fatalf("read pending secret: %v", err)
	}
	if confirmed != nil {
		t.Error("enroll set totp_confirmed_at")
	}
	if bytes.Contains(sealed, secret) {
		t.Error("the stored secret is not encrypted")
	}
	if purpose := ticketPurpose(t, env, ch.MFATicket); purpose != "enroll" {
		t.Errorf("ticket purpose = %q, want enroll", purpose)
	}

	status, header, body := postJSON(t, env.h.public, "/admin-auth/mfa/confirm", "",
		fmt.Sprintf(`{"mfa_ticket":%q,"code":%q}`, ch.MFATicket, env.code(secret)))
	if status != http.StatusOK {
		t.Fatalf("confirm status = %d, want 200 (body %s)", status, body)
	}
	var confirmedBody mfaConfirmWire
	if err := json.Unmarshal([]byte(body), &confirmedBody); err != nil {
		t.Fatalf("confirm body %q is not JSON: %v", body, err)
	}
	if len(confirmedBody.RecoveryCodes) != 10 {
		t.Errorf("recovery codes = %d, want 10", len(confirmedBody.RecoveryCodes))
	}
	if confirmedBody.AccessToken == "" || confirmedBody.User == nil || confirmedBody.User.ID != id {
		t.Errorf("confirm did not end signed in: %+v", confirmedBody)
	}
	cookieFromHeader(t, header, testRefreshCookieName)

	var (
		confirmedAt *time.Time
		recovery    int
		audits      int
	)
	if err := env.db.Pool.QueryRow(t.Context(),
		`SELECT totp_confirmed_at FROM staff_user WHERE id = $1::uuid`, id).Scan(&confirmedAt); err != nil {
		t.Fatalf("read confirmed_at: %v", err)
	}
	if confirmedAt == nil {
		t.Error("totp_confirmed_at is still NULL after confirm")
	}
	if err := env.db.Pool.QueryRow(t.Context(),
		`SELECT count(*) FROM mfa_recovery_code WHERE user_id = $1::uuid AND used_at IS NULL`, id).Scan(&recovery); err != nil {
		t.Fatalf("count recovery codes: %v", err)
	}
	if recovery != 10 {
		t.Errorf("live recovery codes = %d, want 10", recovery)
	}
	if err := env.db.Pool.QueryRow(t.Context(),
		`SELECT count(*) FROM audit_log WHERE action = 'mfa.enroll' AND actor_id = $1`, id).Scan(&audits); err != nil {
		t.Fatalf("count mfa.enroll audits: %v", err)
	}
	if audits != 1 {
		t.Errorf("mfa.enroll audit rows = %d, want 1", audits)
	}

	// The ticket is single-use once confirmed.
	status, _, _ = postJSON(t, env.h.public, "/admin-auth/mfa/confirm", "",
		fmt.Sprintf(`{"mfa_ticket":%q,"code":%q}`, ch.MFATicket, env.code(secret)))
	if status != http.StatusUnauthorized {
		t.Errorf("second confirm with the same ticket = %d, want 401", status)
	}
}

func TestMFAEnrollConfirmViaBearer(t *testing.T) {
	env := newMFAEnv(t)
	id, _, _, _ := env.staff(t, []string{"viewer"}, false)
	tok, err := env.signer.Issue(id, "MFA Staff", []string{"viewer"}, env.now)
	if err != nil {
		t.Fatalf("Issue: %v", err)
	}

	status, _, body := postJSON(t, env.h.public, "/admin-auth/mfa/enroll", tok, `{}`)
	if status != http.StatusOK {
		t.Fatalf("bearer enroll status = %d, want 200 (body %s)", status, body)
	}
	var enrolled mfaEnrollWire
	if err := json.Unmarshal([]byte(body), &enrolled); err != nil {
		t.Fatalf("enroll body: %v", err)
	}
	secret, err := mfa.DecodeSecret(enrolled.Secret)
	if err != nil {
		t.Fatalf("DecodeSecret: %v", err)
	}

	status, header, body := postJSON(t, env.h.public, "/admin-auth/mfa/confirm", tok,
		fmt.Sprintf(`{"code":%q}`, env.code(secret)))
	if status != http.StatusOK {
		t.Fatalf("bearer confirm status = %d, want 200 (body %s)", status, body)
	}
	var confirmed mfaConfirmWire
	if err := json.Unmarshal([]byte(body), &confirmed); err != nil {
		t.Fatalf("confirm body: %v", err)
	}
	if len(confirmed.RecoveryCodes) != 10 {
		t.Errorf("recovery codes = %d, want 10", len(confirmed.RecoveryCodes))
	}
	// Bearer confirmation is the account page's flow: it does not mint a session
	// and must not set a refresh cookie.
	if confirmed.AccessToken != "" {
		t.Error("bearer confirm returned an access token")
	}
	if set := header.Get("Set-Cookie"); set != "" {
		t.Errorf("bearer confirm set a cookie: %q", set)
	}
}

func TestMFARootCannotEnroll(t *testing.T) {
	env := newMFAEnv(t)
	id, _ := env.insertRoot(t, "root-password-5678")
	tok, err := env.signer.Issue(id, "Root MFA", []string{"admin"}, env.now)
	if err != nil {
		t.Fatalf("Issue: %v", err)
	}

	status, _, body := postJSON(t, env.h.public, "/admin-auth/mfa/enroll", tok, `{}`)
	if status != http.StatusForbidden {
		t.Fatalf("root enroll status = %d, want 403 (body %s)", status, body)
	}
}

func TestMFAEnrollRejectsConfirmedFactor(t *testing.T) {
	env := newMFAEnv(t)
	id, _, _, _ := env.staff(t, []string{"viewer"}, true)
	tok, err := env.signer.Issue(id, "MFA Staff", []string{"viewer"}, env.now)
	if err != nil {
		t.Fatalf("Issue: %v", err)
	}

	status, _, body := postJSON(t, env.h.public, "/admin-auth/mfa/enroll", tok, `{}`)
	if status != http.StatusConflict {
		t.Fatalf("confirmed enroll status = %d, want 409 (body %s)", status, body)
	}
	if got := decodeAPIError(t, body); got.Error.Code != "mfa_already_enabled" {
		t.Errorf("code = %q, want mfa_already_enabled", got.Error.Code)
	}
}

func TestMFAConfirmRejectsNoPendingSecret(t *testing.T) {
	env := newMFAEnv(t)
	id, _, _, _ := env.staff(t, []string{"viewer"}, false)
	tok, err := env.signer.Issue(id, "MFA Staff", []string{"viewer"}, env.now)
	if err != nil {
		t.Fatalf("Issue: %v", err)
	}

	status, _, body := postJSON(t, env.h.public, "/admin-auth/mfa/confirm", tok, `{"code":"123456"}`)
	if status != http.StatusConflict {
		t.Fatalf("confirm without enrollment status = %d, want 409 (body %s)", status, body)
	}
	if got := decodeAPIError(t, body); got.Error.Code != "mfa_not_enrolling" {
		t.Errorf("code = %q, want mfa_not_enrolling", got.Error.Code)
	}
}

func TestMFASecretsAreSealedPerUser(t *testing.T) {
	env := newMFAEnv(t)
	idA, _, _, _ := env.staff(t, []string{"viewer"}, false)
	idB, _, _, _ := env.staff(t, []string{"viewer"}, false)

	sealFor := func(id string) []byte {
		t.Helper()
		secret, err := mfa.GenerateSecret()
		if err != nil {
			t.Fatalf("GenerateSecret: %v", err)
		}
		sealed, err := mfa.Seal(env.key, id, secret)
		if err != nil {
			t.Fatalf("Seal: %v", err)
		}
		if _, err := env.db.Pool.Exec(t.Context(),
			`UPDATE staff_user SET totp_secret_enc = $2 WHERE id = $1::uuid`, id, sealed); err != nil {
			t.Fatalf("store sealed secret: %v", err)
		}
		return sealed
	}
	sealedA := sealFor(idA)
	sealedB := sealFor(idB)

	if bytes.Equal(sealedA, sealedB) {
		t.Error("two users' ciphertexts are identical")
	}
	if _, err := mfa.Open(env.key, idA, sealedB); err == nil {
		t.Error("user B's ciphertext opened for user A")
	}
	if _, err := mfa.Open(env.key, idA, sealedA); err != nil {
		t.Errorf("user A's ciphertext did not open for user A: %v", err)
	}
}

func TestMFAMetricsSeriesArePreInitialised(t *testing.T) {
	env := newMFAEnv(t)

	body := metricsBody(t, env.h)
	for _, result := range []string{"verified", "recovery_code", "invalid_code", "invalid_ticket", "enrolled", "error"} {
		if got := counterValue(t, body, "staff_mfa_total", result); got != 0 {
			t.Errorf("staff_mfa_total{result=%q} = %v, want 0 before any request", result, got)
		}
	}
	for _, result := range []string{"mfa_required", "mfa_enrollment_required"} {
		if got := counterValue(t, body, "staff_login_total", result); got != 0 {
			t.Errorf("staff_login_total{result=%q} = %v, want 0 before any request", result, got)
		}
	}
}

func TestMFAMetricsAreCountedByOutcome(t *testing.T) {
	env := newMFAEnv(t)

	// invalid_ticket: an unknown ticket.
	postJSON(t, env.h.public, "/admin-auth/mfa/verify", "", `{"mfa_ticket":"no-such-ticket","code":"123456"}`)

	// verified and invalid_code for a confirmed account.
	_, email, pw, secret := env.staff(t, []string{"live_ops"}, true)
	badTicket := loginTicket(t, env, email, pw)
	postJSON(t, env.h.public, "/admin-auth/mfa/verify", "",
		fmt.Sprintf(`{"mfa_ticket":%q,"code":"000000"}`, badTicket.MFATicket))
	goodTicket := loginTicket(t, env, email, pw)
	postJSON(t, env.h.public, "/admin-auth/mfa/verify", "",
		fmt.Sprintf(`{"mfa_ticket":%q,"code":%q}`, goodTicket.MFATicket, env.code(secret)))

	// enrolled: a full admin enrollment.
	_, adminEmail, adminPW, _ := env.staff(t, []string{"admin"}, false)
	ch := loginTicket(t, env, adminEmail, adminPW)
	_, _, enrollBody := postJSON(t, env.h.public, "/admin-auth/mfa/enroll", "",
		fmt.Sprintf(`{"mfa_ticket":%q}`, ch.MFATicket))
	var enrolled mfaEnrollWire
	if err := json.Unmarshal([]byte(enrollBody), &enrolled); err != nil {
		t.Fatalf("enroll body: %v", err)
	}
	adminSecret, _ := mfa.DecodeSecret(enrolled.Secret)
	postJSON(t, env.h.public, "/admin-auth/mfa/confirm", "",
		fmt.Sprintf(`{"mfa_ticket":%q,"code":%q}`, ch.MFATicket, env.code(adminSecret)))

	body := metricsBody(t, env.h)
	for result, want := range map[string]float64{
		"verified":       1,
		"recovery_code":  0,
		"invalid_code":   1,
		"invalid_ticket": 1,
		"enrolled":       1,
		"error":          0,
	} {
		if got := counterValue(t, body, "staff_mfa_total", result); got != want {
			t.Errorf("staff_mfa_total{result=%q} = %v, want %v", result, got, want)
		}
	}

	// The login metric set grew too: the challenge outcomes are counted there.
	login := metricsBody(t, env.h)
	if got := counterValue(t, login, "staff_login_total", "mfa_required"); got != 2 {
		t.Errorf("staff_login_total{mfa_required} = %v, want 2", got)
	}
	if got := counterValue(t, login, "staff_login_total", "mfa_enrollment_required"); got != 1 {
		t.Errorf("staff_login_total{mfa_enrollment_required} = %v, want 1", got)
	}
}

// TestMFAVerifyAttemptsAreBoundedUnderConcurrency: parallel guesses on one ticket must
// not get past the attempt limit, because each claims its attempt atomically before
// any code is checked.
func TestMFAVerifyAttemptsAreBoundedUnderConcurrency(t *testing.T) {
	env := newMFAEnv(t)
	_, email, pw, _ := env.staff(t, []string{"live_ops"}, true)
	ch := loginTicket(t, env, email, pw)

	const n = 20
	start := make(chan struct{})
	codes := make(chan string, n)
	var wg sync.WaitGroup
	for i := 0; i < n; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			<-start
			_, _, body := postJSON(t, env.h.public, "/admin-auth/mfa/verify", "",
				fmt.Sprintf(`{"mfa_ticket":%q,"code":"000000"}`, ch.MFATicket))
			codes <- decodeAPIError(t, body).Error.Code
		}()
	}
	close(start)
	wg.Wait()
	close(codes)

	counts := map[string]int{}
	for c := range codes {
		counts[c]++
	}
	if counts["invalid_code"] != 5 || counts["invalid_ticket"] != n-5 {
		t.Errorf("outcomes = %v, want exactly 5 invalid_code and %d invalid_ticket", counts, n-5)
	}
	hash := sha256.Sum256([]byte(ch.MFATicket))
	var attempts int
	if err := env.db.Pool.QueryRow(t.Context(),
		`SELECT failed_attempts FROM mfa_ticket WHERE token_hash = $1`, hash[:]).Scan(&attempts); err != nil {
		t.Fatalf("read ticket: %v", err)
	}
	if attempts != 5 {
		t.Errorf("failed_attempts = %d, want 5", attempts)
	}
}
